name: CI/CD feedpoller-func

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DOTNET_VERSION:                 '6.0.x' # Global environment variables
  TEST_FUNC_NAME:                 'oed-test-feedpoller-func'
  PROD_FUNC_NAME:                 'oed-feedpoller-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './published'

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: GitHub metadata
      run: Write-Output "$env:GITHUB_REPOSITORY on $env:GITHUB_REF_NAME by $env:GITHUB_ACTOR"
      shell: pwsh
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    - name: Run Tests
      run: dotnet test --verbosity normal

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-artifacts
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

  deploy-to-test:
    name: Deploy to Test Environment
    needs: build
    runs-on: windows-latest
    environment:
      name: test

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: published-artifacts
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    - name: 'Deploy to Azure Functions (Test)'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: '${{ env.TEST_FUNC_NAME }}'
        slot-name: 'Production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}

  deploy-to-prod:
    name: Deploy to Production Environment
    needs: deploy-to-test
    runs-on: windows-latest
    environment:
      name: production

    steps:
    - name: Await Manual Approval
      if: github.ref == 'refs/heads/main'
      run: Write-Output "Waiting for manual approval..."
      shell: pwsh
      
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: published-artifacts
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    - name: Deploy to Azure Functions (Prod)
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: '${{ env.PROD_FUNC_NAME}}'
        slot-name: 'Production'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
